(module asl-pack/targets/preview-server
  :d "Pure AgentScript WebSocket dev-server orchestrator and hot-reload patch broadcaster for mobile preview."
  :x [PreviewServerSpec
      make-preview-server-spec
      format-hot-reload-patch-frame
      generate-preview-server-script]
  :i [])

(df int-to-string [(n Int64)] -> Str
  :d "Converts integer to string representation."
  (string-from-int64 n))

(dfs PreviewServerSpec
  (:f port Int64 "WebSocket listening port e.g. 8080")
  (:f heartbeat-ms Int64 "Keepalive ping interval in milliseconds")
  (:f watch-dir Str "Directory path monitored for AST updates"))

(df make-preview-server-spec [(port Int64) (watch-dir Str)] -> PreviewServerSpec
  :d "Constructs standard mobile preview dev server specification."
  (PreviewServerSpec
    :port port
    :heartbeat-ms 30000
    :watch-dir watch-dir))

(df format-hot-reload-patch-frame [(target-screen Str) (html-payload Str)] -> Str
  :d "Formats an atomic differential patch frame into compact JSON for the browser simulator."
  (str "{\"type\":\"patch\",\"screen\":\"" target-screen "\",\"html\":\"" html-payload "\"}"))

(df generate-preview-server-script [(spec PreviewServerSpec)] -> Str
  :d "Emits a lightweight standalone Node.js/Bun WebSocket hot-reload server script."
  (let [(p-str (int-to-string (.-port spec)))
        (w-dir (.-watch-dir spec))]
    (str "// Auto-generated by asl-pack mobile preview server\n"
         "const http = require('http');\n"
         "const fs = require('fs');\n"
         "const path = require('path');\n"
         "const PORT = " p-str ";\n"
         "const server = http.createServer((req, res) => {\n"
         "  const file = req.url === '/' ? 'scratch/mobile_preview.html' : req.url.slice(1);\n"
         "  const filePath = path.resolve(process.cwd(), file);\n"
         "  if (fs.existsSync(filePath)) {\n"
         "    res.writeHead(200, { 'Content-Type': file.endsWith('.html') ? 'text/html' : 'text/plain' });\n"
         "    fs.createReadStream(filePath).pipe(res);\n"
         "  } else {\n"
         "    res.writeHead(404);\n"
         "    res.end('Not Found');\n"
         "  }\n"
         "});\n"
         "server.listen(PORT, () => console.log(`ASL Mobile Preview Server active at http://localhost:${PORT}`));\n")))
