(module asl-pack/targets/swift
  :d "Swift Package Manager and Apple iOS/macOS AOT native bridge generator."
  :x [SwiftPackageSpec
      generate-package-swift
      generate-c-bridge-header]
  :i [])

(dfs SwiftPackageSpec
  (:f pkg-name Str "Swift package target name e.g. ASLKit")
  (:f ios-min-version Str "Minimum iOS platform version e.g. v15")
  (:f macos-min-version Str "Minimum macOS platform version e.g. v12")
  (:f c-bridge-header Str "Header filename e.g. ASLBridge.h"))

(df generate-c-bridge-header [(pkg-name Str)] -> Str
  :d "Emits pure C header declarations for AOT compiled AgentScript modules."
  (str "// Auto-generated by @genseam/asl-pack for " pkg-name "\n"
       "#ifndef ASL_BRIDGE_H\n"
       "#define ASL_BRIDGE_H\n\n"
       "#include <stdint.h>\n"
       "#include <stddef.h>\n\n"
       "#ifdef __cplusplus\n"
       "extern \"C\" {\n"
       "#endif\n\n"
       "typedef struct {\n"
       "    const uint8_t *data;\n"
       "    size_t length;\n"
       "} ASLByteBuffer;\n\n"
       "int32_t asl_init(void);\n"
       "ASLByteBuffer asl_eval(const char *module_name, const uint8_t *input_asn, size_t input_len);\n"
       "void asl_free_buffer(ASLByteBuffer buf);\n\n"
       "#ifdef __cplusplus\n"
       "}\n"
       "#endif\n\n"
       "#endif // ASL_BRIDGE_H\n"))

(df generate-package-swift [(spec SwiftPackageSpec)] -> Str
  :d "Generates standard Package.swift manifest linking AOT static library."
  (let [(name (.-pkg-name spec))
        (hdr (.-c-bridge-header spec))]
    (str "// swift-tools-version: 5.9\n"
         "import PackageDescription\n\n"
         "let package = Package(\n"
         "    name: \"" name "\",\n"
         "    platforms: [.iOS(." (.-ios-min-version spec) "), .macOS(." (.-macos-min-version spec) ")],\n"
         "    products: [\n"
         "        .library(name: \"" name "\", targets: [\"" name "\"])\n"
         "    ],\n"
         "    targets: [\n"
         "        .target(\n"
         "            name: \"" name "\",\n"
         "            publicHeadersPath: \"include\",\n"
         "            cSettings: [.headerSearchPath(\"include\")]\n"
         "        )\n"
         "    ]\n"
         ")\n")))
