(module asl-pack/targets/swift
  :d "Swift Package Manager and Apple iOS/macOS AOT native bridge generator."
  :x [SwiftPackageSpec
      SwiftAppSpec
      generate-package-swift
      generate-c-bridge-header
      generate-xcframework-script
      generate-swiftui-entrypoint
      generate-swift-observable-store]
  :i [])

(dfs SwiftPackageSpec
  (:f pkg-name Str "Swift package target name e.g. ASLKit")
  (:f ios-min-version Str "Minimum iOS platform version e.g. v15")
  (:f macos-min-version Str "Minimum macOS platform version e.g. v12")
  (:f c-bridge-header Str "Header filename e.g. ASLBridge.h"))

(dfs SwiftAppSpec
  (:f app-name Str "Application binary and product name e.g. ASLMobileApp")
  (:f bundle-id Str "Apple reverse-DNS bundle identifier e.g. io.genseam.aslmobile")
  (:f ios-min-version Str "Minimum iOS platform version e.g. v16")
  (:f package-name Str "Swift package target name e.g. ASLKit"))

(df generate-c-bridge-header [(pkg-name Str)] -> Str
  :d "Emits pure C header declarations for AOT compiled AgentScript modules."
  (str "// Auto-generated by asl-pack for " pkg-name "\n"
       "#ifndef ASL_BRIDGE_H\n"
       "#define ASL_BRIDGE_H\n\n"
       "#include <stdint.h>\n"
       "#include <stddef.h>\n\n"
       "#ifdef __cplusplus\n"
       "extern \"C\" {\n"
       "#endif\n\n"
       "typedef struct {\n"
       "    const uint8_t *data;\n"
       "    size_t length;\n"
       "} ASLByteBuffer;\n\n"
       "int32_t asl_init(void);\n"
       "ASLByteBuffer asl_eval(const char *module_name, const uint8_t *input_asn, size_t input_len);\n"
       "void asl_free_buffer(ASLByteBuffer buf);\n\n"
       "#ifdef __cplusplus\n"
       "}\n"
       "#endif\n\n"
       "#endif // ASL_BRIDGE_H\n"))

(df generate-package-swift [(spec SwiftPackageSpec)] -> Str
  :d "Generates standard Package.swift manifest linking AOT static library."
  (let [(name (.-pkg-name spec))
        (hdr (.-c-bridge-header spec))]
    (str "// swift-tools-version: 5.9\n"
         "import PackageDescription\n\n"
         "let package = Package(\n"
         "    name: \"" name "\",\n"
         "    platforms: [.iOS(." (.-ios-min-version spec) "), .macOS(." (.-macos-min-version spec) ")],\n"
         "    products: [\n"
         "        .library(name: \"" name "\", targets: [\"" name "\"])\n"
         "    ],\n"
         "    targets: [\n"
         "        .target(\n"
         "            name: \"" name "\",\n"
         "            publicHeadersPath: \"include\",\n"
         "            cSettings: [.headerSearchPath(\"include\")]\n"
         "        )\n"
         "    ]\n"
         ")\n")))

(df generate-xcframework-script [(pkg-name Str) (out-dir Str)] -> Str
  :d "Emits a shell script to build and package a multi-architecture XCFramework for physical devices and simulators."
  (str "#!/usr/bin/env bash\n"
       "set -euo pipefail\n"
       "echo \"Building " pkg-name " multi-arch XCFramework in " out-dir "...\"\n"
       "xcodebuild archive -scheme " pkg-name " -destination \"generic/platform=iOS\" -archivePath \"" out-dir "/ios.xcarchive\" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES\n"
       "xcodebuild archive -scheme " pkg-name " -destination \"generic/platform=iOS Simulator\" -archivePath \"" out-dir "/ios-sim.xcarchive\" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES\n"
       "xcodebuild -create-xcframework \\\n"
       "    -framework \"" out-dir "/ios.xcarchive/Products/Library/Frameworks/" pkg-name ".framework\" \\\n"
       "    -framework \"" out-dir "/ios-sim.xcarchive/Products/Library/Frameworks/" pkg-name ".framework\" \\\n"
       "    -output \"" out-dir "/" pkg-name ".xcframework\"\n"
       "echo \"XCFramework created successfully at " out-dir "/" pkg-name ".xcframework\"\n"))

(df generate-swiftui-entrypoint [(app-name Str)] -> Str
  :d "Emits standard SwiftUI 6 @main application scene entrypoint."
  (str "// Auto-generated by asl-pack for " app-name "\n"
       "import SwiftUI\n\n"
       "@main\n"
       "struct " app-name "App: App {\n"
       "    @State private var store = ASLStateStore()\n\n"
       "    var body: some Scene {\n"
       "        WindowGroup {\n"
       "            ContentView()\n"
       "                .environment(store)\n"
       "        }\n"
       "    }\n"
       "}\n"))

(df generate-swift-observable-store [(store-name Str)] -> Str
  :d "Emits Swift 6 observation framework reactive store binding ASL native memory."
  (str "// Auto-generated by asl-pack for " store-name "\n"
       "import SwiftUI\n"
       "import Observation\n\n"
       "@Observable\n"
       "public final class " store-name " {\n"
       "    public var statePayload: String = \"{}\"\n"
       "    public var isEvaluating: Bool = false\n\n"
       "    public init() {}\n\n"
       "    public func dispatchAction(moduleName: String, actionPayload: String) {\n"
       "        self.isEvaluating = true\n"
       "        let rawBytes = [UInt8](actionPayload.utf8)\n"
       "        let resultBuf = asl_eval(moduleName, rawBytes, rawBytes.count)\n"
       "        if let data = resultBuf.data {\n"
       "            self.statePayload = String(decoding: UnsafeBufferPointer(start: data, count: resultBuf.length), as: UTF8.self)\n"
       "            asl_free_buffer(resultBuf)\n"
       "        }\n"
       "        self.isEvaluating = false\n"
       "    }\n"
       "}\n"))
